name: tempat_makan
description: A Flutter Root project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  app_state_manager:
    path: packages/app_state_manager
  go_router: ^5.1.6
  provider: ^6.0.4
  sign_in:
    path: packages/features/sign_in
  sign_up:
    path: packages/features/sign_up
  onboarding:
    path: packages/features/onboarding
  home:
    path: packages/features/home
  detail:
    path: packages/features/detail
  profile:
    path: packages/features/profile
  search:
    path: packages/features/search
  resources:
    path: packages/resources
  core:
    path: core
  get_it: ^7.2.0
  http: ^0.13.5
  flutter_screenutil: ^5.6.0
  firebase_core: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
